### PR TITLE
added my favorite games

### PR DESCRIPTION
**Pull request by lippelman515**

### CODE REVIEW

**Review by SamBumgardner — CHANGES_REQUESTED** [review]
Something very strange has occurred.

**Review by Startarrot — APPROVED** [review]
Ori is so good

**Review by BlakeEngelbrecht95 — APPROVED** [review]
nice!

**Review by SamBumgardner — APPROVED** [review]
There were never any problems!

**Review by BlakeEngelbrecht95 — APPROVED** [review]

**Pull request merged**
